### ISSUE TITLE
[NEW] - Novos curso DIO

### ISSUE THREAD

**Issue by galvaodev** [CodandoApple/Lista-Maravilhosa-Swift#1]
Novos cursos de swift na Digital Innovation One, muito bom recomento totalmente view code!

Cursos: 
- Criando um aplicativo com swiftUi e combine
- Conhecendo a base do swift

Nível:
Básico/Intermediario

Link:
https://web.digitalinnovation.one/browse?filter=Swift

![Captura de Tela 2021-04-27 às 21 47 27](https://user-images.githubusercontent.com/10669905/116329635-2e676280-a7a2-11eb-91ec-6487f963de30.png)

Criar uma conta totalmente gratuito.

**Comment by reisdev** [comment]
Cursos adicionados com sucesso. Obrigado pela contribuição!
